parameters:

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.



  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Symka\Core\:
    resource: '../*'
    exclude: '../{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
   # tags: ['doctrine.repository_service']

  # controllers are imported separately to make sure services can be injected
  # as action arguments even if you don't extend any base controller class
  Symka\Core\Controller\:
    resource: '../../../src/Controller'
    tags: ['controller.service_arguments']

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones

  symkaLayout:
    class: Symka\Core\Twig\Extension\LayoutExtension
    tags:
     - { name: twig.extension }

  symkaTestTwigHelper:
    class: Symka\Core\Twig\Extension\TestHelperExtension
    tags:
      - { name: twig.extension }

  Symka\Core\Event\Subscriber\CrudSubscriber:
    tags:
      - { name: kernel.event_subscriber }

  form_extension.button_icon:
    class: Symka\Core\Form\Extension\ButtonTypeIconExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }